### ISSUE TITLE
Why does MP need to run /bin/sh/ as Super User?

### ISSUE THREAD

**Issue by ReedOverflow** [iocave/monkey-patch#11]
I'm trying to use the CustomizeUI extension to change sidebar fonts. It relies on Monkey-Patch.

When I run 'Enable Monkey Patch', I click 'Proceed' on it's popup Then Ubuntu pops up
"Authentication is needed to run '/bin/sh' as the super user

I'm reluctant to give anything superuser without clear justification, so I just want to know why? And if it can be documented.

**Comment by knopp** [comment]
It first try to patch the vscode installation under normal account, and if that fails it tries with privileges. On MacOS for example it's quite common that writing to /Applications needs administrator access.

**Comment by ReedOverflow** [comment]
Okay, thank you for the quick answer.
