### ISSUE TITLE
Patching breaks new Insiders build (Win10/macOS, 1.48.0.0)

### ISSUE THREAD

**Issue by disco0** [iocave/monkey-patch#14]
Error messages:

![monkey-patch-crash-win10](https://user-images.githubusercontent.com/13393582/88134241-f3902880-cb98-11ea-9cad-a008b3f4b05c.png)
<img width="1172" alt="monkey-patch-crash-macOS" src="https://user-images.githubusercontent.com/13393582/88134242-f428bf00-cb98-11ea-86bc-00913dc2046b.png">

**Comment by knopp** [comment]
I just pushed 0.1.10 that should fix this. But given that vscode doesn't start at all, you'll need to

1. Reinstall vscode
2. Make sure monkey-patch extension is updated
3. Run the "Enable Monkey-patch" command

**Comment by Hanif1601** [comment]
I got this too recently. Now reinstalling the app again.

**Comment by knopp** [comment]
Make sure  0.1.10 is installed before enabling monkey-patch.

**Comment by disco0** [comment]
Finally switched off my forked patch to v0.1.10 and can confirm its fixed. Thanks!
