### ISSUE TITLE
Monkey Patch does not agree with recent insiders versions

### ISSUE THREAD

**Issue by septsea** [iocave/monkey-patch#19]
I use the latest VS Code Insiders. However, Monkey Patch does not seem to work. I specified what fonts I'd like to use, and I enabled Monkey Patch and Customize UI, but there's no change...
![image](https://user-images.githubusercontent.com/57337516/104249059-a638a800-54a5-11eb-86ff-9db332b9735b.png)
![image](https://user-images.githubusercontent.com/57337516/104249302-23641d00-54a6-11eb-9853-9f6b93d0eccb.png)

**Comment by knopp** [comment]
Please let me know if the problem persists after 0.1.50 gets live.

**Comment by septsea** [comment]
It works now. Thanks!
![image](https://user-images.githubusercontent.com/57337516/104261088-bb223500-54bf-11eb-9b88-2e2027e84f15.png)

**Comment by septsea** [comment]
I just updated VS Code Insiders, but the same thing happened again...

**Comment by knopp** [comment]
Can you check if this persists with 0.1.12?

**Comment by septsea** [comment]
@knopp 
Everything works pretty well! I cannot help wondering what on earth makes the extensions malfunction, by the way.

**Comment by knopp** [comment]
The extension heavily relies on vscode internals. So every time there is a refactor in vscode it can potentially break monkey-patch.

**Comment by knopp** [comment]
In general using customize-ui/monkey-patch with insiders is not a very good idea, since I can't always fix the issue immediately as it happens.

**Comment by septsea** [comment]
Well, I just like trying new things on my own PC. VS Code is more a toy than a text editor for me. If I did not know the existence of your two extensions, I would always have to replace some files manually—I also tried to write an extension to apply my changes automatically, but I failed. I appreciate your work very much. 😁

**Comment by septsea** [comment]
Excuse me. I am here to say that the extension does not work in the latest VSC-insiders! I sound like a tester who knows nothing about JavaScript. 🤣

**Comment by septsea** [comment]
Hey! Long time no see. The extension does not work again! Version: 1.58.0-insider.

**Comment by knopp** [comment]
Can you try with monkey patch 0.1.14  and customize-ui 0.1.54? They should be available soon. You will need to restart VScode and it should ask you to re-apply MonkeyPatch.

**Comment by knopp** [comment]
I just tried upgrading 0.1.13 and 0.1.53 (which doesn't work) to 0.1.14 and 0.1.54 and it seems to work fine. Which platform are you on?

**Comment by bi-functor** [comment]
I'm on Windows. I've tried disabling MP 0.1.14 before uninstalling, uninstalling without disabling, and nothing seems to work. Disabling without uninstalling either.

**Comment by knopp** [comment]
My bad. There is a problem with windows path separators I didn't expect. I'm working on it.

**Comment by knopp** [comment]
@bi-functor, can you let me know if 0.1.15 works for you once available? (should be in few minutes)

**Comment by bi-functor** [comment]
Yeah, MP 0.1.15 works now! Thanks for the quick fix!

**Comment by septsea** [comment]
Good morning. Thank you so much! @knopp @bi-functor

**Comment by rbadapanda** [comment]
Please close this ticket if it is fixed.
