### ISSUE TITLE
Doesn't load modules anymore (1.54.1) 

### ISSUE THREAD

**Issue by seivan** [iocave/monkey-patch#21]
```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (13 hrs ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

I get the usual `[Extension Host] Monkey Patch is active.` and it does seem to replace the bootstrapper.
But my [extension](https://github.com/seivan/swipe-to-navigate/blob/master/src/extension.ts) doesn't seem to run.

For now I disabled my extension and just use this configuration to load it directly for debugging purposes but to no avail. 
```json
"monkeyPatch.folderMap": {
    "my-custom-modules" : "~/my-custom-modules",
},
```

On a side note, do you know if there is a way to log from a mainprocess into the console or even pop an alert.
I can't tell if it's API breakage or the patches don't even load at all.

**Comment by knopp** [comment]
Which monkey-patch and customize-ui versions do you have installed?

**Comment by seivan** [comment]
I am not using `customize-ui`, I'm using the latest monkey-patch `v0.1.12` as a dependency. It's worked until recent update to vscode.

**Comment by knopp** [comment]
It likely fails because there is no longer `vs/code/electron-main/window` that can be imported. It got moved to `vs/platform/windows/electron-main/window` recently.

**Comment by seivan** [comment]
@knopp Yep yep, I just saw it a second ago. My define isn't being triggered, wish there was a better way to capture those. 
I added an alert at the top just to trigger an error and it seems it runs my script, but it doesn't go into the function. 

Do you think it's feasible for `monkey-patch` to keep track of these things to at least throw errors? 
Though we're in uncharted territory, not even getting an error is somewhat scary. 
Would it be a good idea to make copies or references of some kind to these file under controlled names, so even if the vscode team changes things around, at least monkey-patch could notify that some stuff has changed in the console or even throw an error?

**Comment by seivan** [comment]
@knopp Anyway you solved my problem, thanks!

**Comment by knopp** [comment]
To be honest I'm not exactly sure why the error isn't logged from the loader, I agree that this should be improved, if at all possible.

**Comment by seivan** [comment]
@knopp To be fair, the loader actually does its thing, it loads the script, what would be needed is before loading making sure that the common files like `vs/platform/windows/electron-main/window` haven't been moved around. 
It wouldn't help much in terms of preventing errors, but it would help capturing them. I wasn't even sure the scripts were loaded at all until I just wrote some garbage syntax and got a vscode error, just to see the patches are loaded. 

Either way, do you know a better approach to logging than 
```js
    function logger(mainWindow, s) {
        console.log(s);
        mainWindow._win.webContents.executeJavaScript(`console.log("${s}")`);
    }
```
