### ISSUE TITLE
Failed to enable MP due to Read-only File System

### ISSUE THREAD

**Issue by delvinwidjaja** [iocave/monkey-patch#23]
Hi! I'm trying to enable Monkey Patch but I got this following error:

![Screenshot 2021-04-06 at 16 09 30](https://user-images.githubusercontent.com/44110031/113724278-7b4fa000-96f2-11eb-916c-5d939c21590b.png)

How do I fix this? Thank you for your help 😃 

Tried this on:
VSCode: 1.50.0
MacOS: BigSur 11.0.1

**Comment by knopp** [comment]
You are either trying to run VSCode from Downloads folder, or it still has the quarantine flag. Please see

https://github.com/iocave/monkey-patch/issues/6

**Comment by delvinwidjaja** [comment]
It works. thanks!
