### ISSUE TITLE
Monkey patch makes the explorer panel blank on the latest insider (version: 1.64.0-insider)

### ISSUE THREAD

**Issue by rbadapanda** [iocave/monkey-patch#35]
Version: 1.64.0-insider
Commit: a06afb22ce06dbd4f01d3bb5bf946e08bff55180
Date: 2022-01-10T05:14:47.227Z (11 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

This is just a heads up. There may be more breaking changes for ex: status bar moves from bottom to top etc.

**Comment by knopp** [comment]
Can you test this once 0.1.56 is online?

**Comment by rbadapanda** [comment]
Sure, please let me know when it is out and where can i get it ( unless it is being released to the extension marketplace )

[Sent from mobile.   i-typos; I-Apologize.]

**Comment by knopp** [comment]
It has been released and should be available now.

**Comment by rbadapanda** [comment]
I don’t see v 0.1.56 but I see the issue with the latest version of the monkey patch ( 0.1.16 )

[Sent from mobile.   i-typos; I-Apologize.]

**Comment by knopp** [comment]
0.1.56 is customize ui version.  Sorry for the confusion.

**Comment by rbadapanda** [comment]
Nevermind, I with customize UI version #0.1.56, the issue is gone.

Closing the issue.
