### ISSUE TITLE
Monkey patch fails with VS 1.70.0-insider

### ISSUE THREAD

**Issue by rbadapanda** [iocave/monkey-patch#45]
Monkey Patch failed: Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html'

Version: 1.70.0-insider
Commit: 3104db414c8fedcf6e4493f14da7df0b7413853a
Date: 2022-07-08T05:16:29.757Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by knopp** [comment]
Please let me know if this works with monkey-patch 0.1.17 (should be available soon).

**Comment by rbadapanda** [comment]
it worked with v. v0.1.18
