### ISSUE TITLE
Fails with VS Code 1.69

### ISSUE THREAD

**Issue by janekb04** [iocave/monkey-patch#46]
After enabling the extension, the editor no longer works (blank window). `—verbose` says that `vs/code/electron-browser/workbench/workbench-monkey-patch.html` cannot be found.

I am using the latest release (0.1.17).

Everything worked fine until VS Code update itself and the extension this morning.

**Comment by janekb04** [comment]
I tried reinstalling VS Code, reinstalling the extension and deleting the extension's folder inside `globalStorage`, but none of this helped.

**Comment by knopp** [comment]
Can you redownload vscode and then reapply monkey-patch after 0.1.18 is available (I just published it now)?

**Comment by soundnotation** [comment]
Facing black screen issue after upgrading VS Code to 1.69.0 and clicking on Restart (Monkey Patch notification) after that.
My `code --verbose` says:
```
"Uncaught (in promise) TypeError: Cannot convert undefined or null to object", source: vscode-file://vscode-app/c:/Users/***/AppData/Roaming/Code/User/globalStorage/iocave.monkey-patch/modules/browser-entrypoint.js (22)
```

**Comment by soundnotation** [comment]
Seems to work for me now. Thanks!

**Comment by janekb04** [comment]
After updating, everything is fine again. Thanks, this was probably my fastest-resolved issue ticket ever. My VS Code has its custom UI once again.

<img width="1273" alt="CleanShot 2022-07-08 at 11 26 06@2x" src="https://user-images.githubusercontent.com/13035076/177962047-a5e67f10-cba3-4b18-9413-200b36701feb.png">
