### ISSUE TITLE
Enable failed?

### ISSUE THREAD

**Issue by exec228** [iocave/monkey-patch#5]
Salut!

> Monkey Patch failed: Error: Command failed: C:\Scratch\66349159-2c61-4da5-b649-92f26a358731\script.cmd
VS Codium 1.39.2, Windows 10 x64

>Monkey Patch failed: Error: Command failed: C:\Scratch\32a80c7a-7739-489c-ad68-dc9cf0b8a4a7\script.cmd
VS Code 1.39.2, Windows 10 x64

What can I do?
I urge for Customize UI, because default fonts of UI make my eyes bleeding.

Thank you!

**Comment by knopp** [comment]
I'm not quite sure why the script command fails. Maybe you could try to run it manually to see what the error is?

**Comment by exec228** [comment]
Thank you!

I see that fullpaths I mentionned above seem to be absolutely temporary. I'd say fleeing, blinking, femtosecond. ;-)

Long story short: there is no such files in my system already, immediately after I got this pop-up error.

What should I do? Please, advise.

**Comment by knopp** [comment]
Is the file there *before* you close the popup error? Does vscode have permission to write in that temporary folder at all?

**Comment by knopp** [comment]
Actually, nevermind. It seems that the file is removed *before* error message is displayed. You can manually edit the extension code though. Go to your vscode extension folder (i.e. ~/.vscode/extensions/iocave.monkey-patch-<version>/out) and edit the script.js file. You can remove 
` fs_1.rimrafUnlink(this.folder);` code from the `cleanup` method and the file should be left there after error.

**Comment by exec228** [comment]
I can try in 15 minutes.

I'm pretty sure that global tempfolder, as well as personal user's temp-folder (both are located in the same C:\Scratch\ at the same time) are with high degree of certainity are available for all and any file operations for all and any applications :-)

**Comment by exec228** [comment]
cd "C:\Scratch\37e14861-46ff-4c06-bef5-5293a9114be1"
copy /Y "bootstrap-amd.js---ddb37f01-3dfb-4a74-a709-b6086c0331a4" "d:\EndUser\Programs\Programming\VSCodium\resources\app\out\bootstrap-amd.js"
copy /Y "workbench.html---f47107df-883c-4ec0-9894-df191ca86926" "d:\EndUser\Programs\Programming\VSCodium\resources\app\out\vs\code\electron-browser\workbench\workbench-monkey-patch.html"

First three files do exist.
The last one does not:
>C:\Scratch\37e14861-46ff-4c06-bef5-5293a9114be1>type "d:\EndUser\Programs\Programming\VSCodium\resources\app\out\vs\code\electron-browser\workbench\workbench-monkey-patch.html"
> The system cannot find the file specified.

**Comment by exec228** [comment]
To whom it may concern.

I wrote a simple batch
CALL script.cmd
IF ERRORLEVEL 5 ECHO 5!
IF ERRORLEVEL 4 ECHO 4!
IF ERRORLEVEL 3 ECHO 3!
IF ERRORLEVEL 2 ECHO 2!
IF ERRORLEVEL 1 ECHO 1!
IF ERRORLEVEL 0 ECHO 0!

Result is
C:\Scratch\ee36a404-2746-4ae4-ab77-56bcc89fb969>IF ERRORLEVEL 5 ECHO 5!
C:\Scratch\ee36a404-2746-4ae4-ab77-56bcc89fb969>IF ERRORLEVEL 4 ECHO 4!
C:\Scratch\ee36a404-2746-4ae4-ab77-56bcc89fb969>IF ERRORLEVEL 3 ECHO 3!
C:\Scratch\ee36a404-2746-4ae4-ab77-56bcc89fb969>IF ERRORLEVEL 2 ECHO 2!
C:\Scratch\ee36a404-2746-4ae4-ab77-56bcc89fb969>IF ERRORLEVEL 1 ECHO 1!
C:\Scratch\ee36a404-2746-4ae4-ab77-56bcc89fb969>IF ERRORLEVEL 0 ECHO 0!
0!

Id est overall result of this batch is 0

**Comment by eh8** [comment]
Also encountering enable failure

**Comment by knopp** [comment]
Well, in your case it seems like a problem with the [sudo-prompt](https://www.npmjs.com/package/sudo-prompt) package. I'm not quite sure what's wrong here. I think I tested this with ubuntu and it did prompt for password properly. 

The install process basically consists of generating a script file and then launching the script file using sudo-prompt (if necessary). The code to do that is very simple (out/script.js) so the issue might be that the sudo-prompt package doesn't work properly on your system.

**Comment by eh8** [comment]
I thought so as well, but the failure occurs when I punch in my password to authenticate Monkey Patch.

I reinstalled sudo-prompt to see if that was the issue but it stills throws me that error. Let me know if I can provide any additional info!

**Comment by knopp** [comment]
Well, the error message you get (User did not grant permission.) comes from [sudo-prompt](https://github.com/jorangreef/sudo-prompt/blob/3bfa62163b59e45111436c695ee8e7e2befbe310/index.js#L670). So it obviously doesn't seem to work on your computer. You can try to manually ensure that your user account has permission  to modify vscode installation, in which case sudo-prompt should not be used.

**Comment by eh8** [comment]
Yup, reinstalled Ubuntu and everything is ok now :)

**Comment by divinespear** [comment]
> Actually, nevermind. It seems that the file is removed _before_ error message is displayed. You can manually edit the extension code though. Go to your vscode extension folder (i.e. ~/.vscode/extensions/iocave.monkey-patch-0.1.7/out) and edit the script.js file. You can remove
> ` fs_1.rimrafUnlink(this.folder);` code from the `cleanup` method and the file should be left there after error.

Chrome OS crostini has smiler problem. (there is no polkit)
so I keep generated script via this method, and run it manually. works well.

**Comment by eh8** [comment]
In my case, I found that I had to install vs-code from official repos, and
not snap. Probably had something to do with containerization.

**Comment by jnunderwood** [comment]
FWIW, I have the same problem. I'm using the `snap` installation on Ubuntu.

**Comment by knopp** [comment]
And the answer is still same. When running vscode from container monkey-patch can not alter the installation, because it's running from virtual read-only volume.

**Comment by junaidnasir** [comment]
wasn't working on mac, moved vscode to application folder and now it's working

**Comment by PaulMichaelG** [comment]
New to Linux... snap installation on elementaryOS was giving the same error. Reinstalled VSCode via apt / .deb package and got it working.

**Comment by stillzombie** [comment]
on mac when i tried to enable monkey patch i got this:

Monkey Patch failed: Error: Command failed: /bin/sh /var/folders/56/7y1xg6k913j9yn9x570w0zx40000gq/T/8ad82830-06d0-4b5a-b482-e5af93e4a3db/script.sh cp: /private/var/folders/56/7y1xg6k913j9yn9x570w0zx40000gq/T/AppTranslocation/23F69B3F-4E92-432B-A344-3DF259F75EA8/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.monkey-patch.backup: Read-only file system cp: /private/var/folders/56/7y1xg6k913j9yn9x570w0zx40000gq/T/AppTranslocation/23F69B3F-4E92-432B-A344-3DF259F75EA8/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js: Read-only file system cp: /private/var/folders/56/7y1xg6k913j9yn9x570w0zx40000gq/T/AppTranslocation/23F69B3F-4E92-432B-A344-3DF259F75EA8/d/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench-monkey-patch.html: Read-only file system


any idea what could be the issue?

**Comment by knopp** [comment]
You need to move vscode out of ~/Downloads folder (or wherever else it got downloaded), because otherwise macOS runs it from read-only virtual volume (AppTranslocation)

**Comment by stillzombie** [comment]
> You need to move vscode out of ~/Downloads folder (or wherever else it got downloaded), because otherwise macOS runs it from read-only virtual volume (AppTranslocation)

ah thanks a lot, yeap that was exactly my issue. working perfect now, thanks

**Comment by zsy619** [comment]
Monkey Patch failed: Error: Command failed: /bin/sh /var/folders/pm/1qxqkz7n0s5b77dt50h0nzh80000gn/T/4553b851-ad41-4025-bdc3-df397fcb005d/script.sh
cp: /private/var/folders/pm/1qxqkz7n0s5b77dt50h0nzh80000gn/T/AppTranslocation/F319E9E1-B8F1-475B-8E74-65A122F8ECB0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-amd.js.monkey-patch.backup: Read-only file system
cp: /private/var/folders/pm/1qxqkz7n0s5b77dt50h0nzh80000gn/T/AppTranslocation/F319E9E1-B8F1-475B-8E74-65A122F8ECB0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-amd.js: Read-only file system
cp: /private/var/folders/pm/1qxqkz7n0s5b77dt50h0nzh80000gn/T/AppTranslocation/F319E9E1-B8F1-475B-8E74-65A122F8ECB0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench-monkey-patch.html: Read-only file system

**Comment by EricPlayZ** [comment]
A fix for the original issue:

Locate `script.js` in i.e. `.vscode/extensions/iocave.monkey-patch-0.1.11/out` and open it.
In each of the functions `copy`, `move` and `rm`, instead of using `"${pathFrom}"`, use `"${this.folder}\\${pathFrom}"`. Now you can restart VSCode and try using Enable Monkey Patch again.

I thought of this since VSCode is installed on my G: drive, so doing `cd C:\Users\.....` will cd to that directory but the drive letter won't change unless you do `C:`. It's always better to work with absolute paths for stuff like this I guess (+ you can also shorten the script up by deleting the line which adds the `cd` line

**Comment by anburocky3** [comment]
I can confirm this issue. It exists on `VSCode` snap package

**Comment by HuaiYu-Chao** [comment]
> A fix for the original issue:
> 
> Locate `script.js` in e.g. `.vscode/extensions/iocave.monkey-patch-0.1.11/out` and open it.
> In the `copy` function, instead of using `"${pathFrom}"`, use `"${this.folder}\\${pathFrom}"`. You can also do this for the other 2 functions (`move`, `rm`) but they're not used so it's pointless.
> 
> Now you can restart VSCode and try using Enable Monkey Patch again.
> 
> I thought of this since VSCode is installed on my G: drive, so maybe it ran `script.cmd` inside G: instead of running it from C, so doing `cd C:\Users\.....` will cd to that directory but the drive letter won't change unless you do `C:`. It's always better to work with absolute paths for stuff like this I guess (+ you can also shorten the script up by deleting the line which adds the `cd` line)

@EricPlayZ I had the same problem with my VSCode installed at default position (`C:\......`). My temp directory was set to `D:\temp`, though.  Since I can't find the `script.js`, I just set my temp dir back to the default and the problem was solved.

I'm not familiar with Windows commands, but I think your fix is probably correct, if not totally.
Thank **you** very much, and of course thanks to the **authors**.

**Comment by EricPlayZ** [comment]
> @EricPlayZ I had the same problem with my VSCode installed at default position (`C:\......`). My temp directory was set to `D:\temp`, though. Since I can't find the `script.js`, I just set my temp dir back to the default and the problem was solved.
> 
> I'm not familiar with Windows commands, but I think your fix is probably correct, if not totally.
> Thank **you** very much, and of course thanks to the **authors**.
Yup, same issue there. VSCode was installed in drive, temp folder was in another, which caused the script to not change directories properly, so editing it fixes the issue.

**Comment by icetbr** [comment]
Linux workaround (tested on Ubuntu)

`sudo chown -R YOURUSER:YOURUSER /usr/share/code/resources`

Now you can enable it. Might need to redo this each vscode update

**Comment by mwamodo** [comment]
> Linux workaround (tested on Ubuntu)
> 
> `sudo chown -R YOURUSER:YOURUSER /usr/share/code/resources`
> 
> Now you can enable it. Might need to redo this each vscode update

This will break ubuntu 'sudo' you can not change the owner of a file in /usr

**Comment by icetbr** [comment]
Define "break"? So far no problems. At most it will affect something VsCode related, i don't see any problems to "sudo"

**Comment by tukusejssirs** [comment]
> Linux workaround (tested on Ubuntu)
> 
> `sudo chown -R YOURUSER:YOURUSER /usr/share/code/resources`
> 
> Now you can enable it. Might need to redo this each vscode update

Alternative using ACL: `sudo setfacl -Rm "u:$USER:rwx" /usr/share/codium/resources`
