### ISSUE TITLE
macOS ventura v13.0: Operation not permitted

### ISSUE THREAD

**Issue by nayyarnishant** [iocave/monkey-patch#53]
Hi,

Since the update of macOS to v13.0 with Monkey-Patch `v0.1.23`.

```sh
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

I am getting below error:

```sh
Monkey Patch failed: Error: Command failed: /bin/sh /var/folders/j7/zntnxhkd1qq4l7nn5kbz4w6h0000gn/T/46299b26-50f7-431b-bc1a-7c59aca8c16e/script.sh 
cp: /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.monkey-patch.backup: Operation not permitted 
cp: /Applications/Visual Studio Code.app/Contents/Resources/app/out/main.js.monkey-patch-backup: Operation not permitted cp: /Applications/Visual Studio Code.app/Contents/Resources/app/out/main.js: Operation not permitted 
cp: /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js: Operation not permitted 
cp: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench-monkey-patch.html: Operation not permitted
```

**Comment by brouk2426** [comment]
In my case, I set the permission and it worked

`$ sudo chown -R $(whoami) /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

**Comment by nayyarnishant** [comment]
> In my case, I set the permission and it worked
> 
> `$ sudo chown -R $(whoami) /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`
> 
> my os is ventura too

Tried the command, it fails with `chown: /Applications/Visual Studio Code.app/Contents/*: Operation not permitted`.

The issue still prevails.

**Comment by brouk2426** [comment]
You have to set `Full Disk Access`. Set the permissions of the terminal you are using. 
![image](https://user-images.githubusercontent.com/48667021/199688534-dd5e570a-c19a-40c6-8e45-d5d264240c40.png)

**Comment by nayyarnishant** [comment]
> You have to set `Full Disk Access`. Set the permissions of the terminal you are using.
> ![image](https://user-images.githubusercontent.com/48667021/199688534-dd5e570a-c19a-40c6-8e45-d5d264240c40.png)

And that was the missing bit. Works now, many thanks @brouk2426

**Comment by brouk2426** [comment]
@nayyarnishant Good! :)

**Comment by mattpilott** [comment]
In a fresh install of vscode 1.73.1 I get this on Ventura 13.1
