### ISSUE TITLE
Catalina Read-only file system

### ISSUE THREAD

**Issue by alanzchen** [iocave/monkey-patch#6]
```
Monkey Patch failed: Error: Command failed: /bin/sh /var/folders/09/zy13f7491k71jl4lg5cwk3fw0000gn/T/1eaf7875-55ff-4d3d-85b8-1b3d73f8ed87/script.sh cp: /private/var/folders/09/zy13f7491k71jl4lg5cwk3fw0000gn/T/AppTranslocation/BD8A7E64-C833-4047-BCCD-E4F1914A6EA4/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.monkey-patch.backup: Read-only file system cp: /private/var/folders/09/zy13f7491k71jl4lg5cwk3fw0000gn/T/AppTranslocation/BD8A7E64-C833-4047-BCCD-E4F1914A6EA4/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js: Read-only file system cp: /private/var/folders/09/zy13f7491k71jl4lg5cwk3fw0000gn/T/AppTranslocation/BD8A7E64-C833-4047-BCCD-E4F1914A6EA4/d/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench-monkey-patch.html: Read-only file system
```

I guess it's a Catalina problem but not sure how to fix it.

**Comment by knopp** [comment]
Did you copy vscode to /Applications folder? It seems like you might be running vscode from the ~/Downloads folder and that it is still quarantined, and thus vscode can not modify the bundle.

**Comment by alanzchen** [comment]
I was running it in /Downloads but later moved it to ~/Applications

I will just reboot and try again.

**Comment by knopp** [comment]
It seems that it still may have the quarantine flag set, which would cause macOS to run it from read only filesystem. You can remove the flag manually

```
xattr -d com.apple.quarantine <path-to-vscode.app>
```

**Comment by alanzchen** [comment]
Just ran `xattr -d com.apple.quarantine ~/Applications/Visual\ Studio\ Code.app`, same error

**Comment by knopp** [comment]
Does the bundle have valid code signature? What does `codesign -dv <path-to-vscode.app>` say?

**Comment by knopp** [comment]
In any case, this doesn't seem to have anything with catalina read-only volume. App transolaction (when untrusted app is running from read-only location) has been around since 10.12. However under normal circumstances vscode should not be considered untrusted (it should not have the quarantine flag and valid code signature), so I'm not quite sure why it is in your case. What version do you have installed? Can it auto-update itself? (this should break auto-updating as well)

**Comment by alanzchen** [comment]
`xattr -dr com.apple.quarantine ~/Applications/Visual\ Studio\ Code.app` did the trick. Notice it's `-`-dr` here.

See https://github.com/Microsoft/vscode/issues/7426
