### ISSUE TITLE
Can't run the patch because of Catalina's new R/O protection

### ISSUE THREAD

**Issue by fralyx** [iocave/monkey-patch#9]
Monkey Patch failed: Error: Command failed: /bin/sh /var/folders/1k/fc99xfks2zdff9xn_fg7ymt80000gn/T/541969d3-6ef4-48bb-b4f2-d6ce605a423e/script.sh
cp: /private/var/folders/1k/fc99xfks2zdff9xn_fg7ymt80000gn/T/AppTranslocation/14F8B44C-C70B-4C18-BD28-5799D7FB31C6/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.monkey-patch.backup: Read-only file system
cp: /private/var/folders/1k/fc99xfks2zdff9xn_fg7ymt80000gn/T/AppTranslocation/14F8B44C-C70B-4C18-BD28-5799D7FB31C6/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js: Read-only file system
cp: /private/var/folders/1k/fc99xfks2zdff9xn_fg7ymt80000gn/T/AppTranslocation/14F8B44C-C70B-4C18-BD28-5799D7FB31C6/d/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench-monkey-patch.html: Read-only file system

I was on Mojave and now upgrading to Catalina, even with SIP disabled, the root is still on read-only protection.

**Comment by knopp** [comment]
This usually happens when running quarantined bundles.

Try removing the quarantine flag from vscode bundle using xattr . 

```
xattr -dr com.apple.quarantine <path-to-vscode.app>
```

**Comment by fralyx** [comment]
Worked like a charm, thanks
